//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmadAghazadeh.Shop.CustomerContext.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AhmadAghazadeh.Shop.CustomerContext.Resources.ExceptionResource", typeof(ExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس اجباری است.
        /// </summary>
        public static string AddressLineRequiredException {
            get {
                return ResourceManager.GetString("AddressLineRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس نمی تواند خالی باشد.
        /// </summary>
        public static string AddressRequiredException {
            get {
                return ResourceManager.GetString("AddressRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر اجباری هست.
        /// </summary>
        public static string CityIdRequiredException {
            get {
                return ResourceManager.GetString("CityIdRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت ایمیل را صحیح وارد کنید.
        /// </summary>
        public static string EmailInvalidFormatException {
            get {
                return ResourceManager.GetString("EmailInvalidFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل اجباری است.
        /// </summary>
        public static string EmailRequiredException {
            get {
                return ResourceManager.GetString("EmailRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اجباری است.
        /// </summary>
        public static string FirstNameRequiredException {
            get {
                return ResourceManager.GetString("FirstNameRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی اجبار است.
        /// </summary>
        public static string LastNameRequiredException {
            get {
                return ResourceManager.GetString("LastNameRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام کارکترهای کد ملی باید عدد باشد.
        /// </summary>
        public static string NationalCodeAllChartersIsDigitException {
            get {
                return ResourceManager.GetString("NationalCodeAllChartersIsDigitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی تکرار است.
        /// </summary>
        public static string NationalCodeDuplicateException {
            get {
                return ResourceManager.GetString("NationalCodeDuplicateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول کد ملی باید 10 رقم باشد.
        /// </summary>
        public static string NationalCodeLengthInvalidException {
            get {
                return ResourceManager.GetString("NationalCodeLengthInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی اجباری است.
        /// </summary>
        public static string NationalCodeRequiredException {
            get {
                return ResourceManager.GetString("NationalCodeRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول پسورد باید بیشتر از 6 باشد.
        /// </summary>
        public static string PasswordLengthUpperThanSixException {
            get {
                return ResourceManager.GetString("PasswordLengthUpperThanSixException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز اجباری است.
        /// </summary>
        public static string PasswordRequiredException {
            get {
                return ResourceManager.GetString("PasswordRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل صحیح نیست.
        /// </summary>
        public static string PhoneNumberInvalidException {
            get {
                return ResourceManager.GetString("PhoneNumberInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی اجباری است.
        /// </summary>
        public static string PostalCodeRequiredException {
            get {
                return ResourceManager.GetString("PostalCodeRequiredException", resourceCulture);
            }
        }
    }
}
