// <auto-generated />
using System;
using AhmadAghazadeh.Shop.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AhmadAghazadeh.Shop.Persistence.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20200721115630_FirstInit")]
    partial class FirstInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AhmadAghazadeh.Shop.CustomerContext.Domain.Customers.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("NVarChar250");

                    b.Property<int>("CityId")
                        .HasColumnType("Int");

                    b.Property<string>("Coordinate")
                        .HasColumnType("NVarChar25");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<string>("PostalCode")
                        .HasColumnType("Char10");

                    b.Property<string>("Telephone")
                        .HasColumnType("Char11");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Address","Shop");
                });

            modelBuilder.Entity("AhmadAghazadeh.Shop.CustomerContext.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVarChar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVarChar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVarChar(50)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("Char(10)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("Int");

                    b.HasKey("Id");

                    b.ToTable("Customer","Shop");
                });

            modelBuilder.Entity("AhmadAghazadeh.Shop.CustomerContext.Domain.Customers.Address", b =>
                {
                    b.HasOne("AhmadAghazadeh.Shop.CustomerContext.Domain.Customers.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
